import { Project } from "@/types/project";

/**
 * @description プロジェクトデータの設定
 */
export const projects: Project[] = [
  {
    id: "ポートフォリオサイト",
    title: "ポートフォリオサイト",
    description: "私についての情報を紹介するポートフォリオサイトです。",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "react-icons",
      "Jotai",
      "clsx",
      "tailwind-merge",
      "ESLint",
      "Prettier",
      "nvm",
    ],
    githubUrl: "https://github.com/kmjak/portfolio",
    imageUrl: "/portfolio.png",
    featured: false,
  },
  {
    id: "Portful",
    title: "Portful",
    description:
      "エンジニア特化の就活プラットフォームPortful。学生・学校・企業を繋ぎ、成績連携であなたのスキルを証明。未来のキャリアに繋がる出会いを創出します。",
    technologies: [
      "Next.js",
      "Express.js",
      "オニオンアーキテクチャ",
      "TypeScript",
      "Tailwind CSS",
      "Jotai",
      "clsx",
      "tsyringe",
      "tailwind-merge",
      "Firebase",
      "Supabase",
      "react-hook-form",
      "ESLint",
      "Prettier",
      "nvm",
    ],
    githubUrl: "https://github.com/kmjak/portful",
    featured: true,
  },

  {
    id: "Raiders CTF",
    title: "Raiders CTF",
    description:
      "個人開発やチーム開発で習得したWeb開発のスキルと学校で習得したセキュリティ知識を活かして開発した、CTFの開催を行いました。また、現在は2026年度のCTFの開催に向けて準備を進めているため、2025年度のCTFの認証機能を停止しております。",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "AWS Amplify",
      "DynamoDB",
      "Cognito",
      "Lambda",
      "S3",
      "ECS",
      "ECR",
      "Step Functions",
      "ESLint",
      "Echarts",
    ],
    liveUrl: "https://raidersctf.com",
    imageUrl: "/raidersctf.png",
    featured: false,
  },
  {
    id: "人口構成アプリ",
    title: "人口構成アプリ",
    description:
      "株式会社yumemiのフロントエンドコーディングテスト。人口構成データを可視化するアプリケーションで、ユーザーが地域ごとの人口構成を簡単に確認できるように設計されています。また、AWS AppSyncを使用してリアルタイムでデータを取得し、共同作業を実現しております。",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "AWS AppSync",
      "GraphQL",
      "DynamoDB",
      "Jotai",
      "Jest",
      "ESLint",
      "Prettier",
      "react-chartjs-2",
    ],
    githubUrl: "https://github.com/kmjak/yumemi-coding-test-2025-04",
    liveUrl: "https://main.d8adpzg0m7kgj.amplifyapp.com/",
    imageUrl: "/yumemi-frontend.png",
    featured: false,
  },
  {
    id: "Raiders ALG",
    title: "Raiders ALG",
    description:
      "Progateハッカソン Powered By AWS 2025.03において特別賞受賞。初学者向けの競技プログラミングプラットフォーム。コード提出時のコードのフィードバックや補完機能が充実したwebエディタを実装しております。また、ハッカソン期間内は、AWSが使い放題ということもあり、AWSの各種サービスを活用して開発を行いました。そのため、期間外となった今、開発を一時停止しております。",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "AWS Amplify",
      "SQS",
      "Fargate",
      "ECS",
      "ECR",
      "Step Functions",
      "AWS Lambda",
      "AWS DynamoDB",
      "Go",
      "clsx",
      "tailwind-merge",
    ],
    githubUrl: "https://github.com/OCA-Hackathon/2025-03-Progate-Hackathon",
    imageUrl: "/raidersalg.png",
    featured: true,
  },
  {
    id: "Aurora Chat",
    title: "Aurora Chat",
    description:
      "AWSのDynamoDBとAppSyncを活用したリアルタイムチャットアプリ。GraphQLを使用したデータ取得と、リアルタイム通信を実現しています。",
    technologies: [
      "Next.js",
      "AWS",
      "Tailwind CSS",
      "GraphQL",
      "DynamoDB",
      "AppSync",
      "Cognito",
      "ESLint",
    ],
    imageUrl: "/aurora.png",
    featured: false,
  },
  {
    id: "SketchEase",
    title: "SketchEase",
    description:
      "競技プログラミングで習得したBFSを活用して開発した、ブラウザ上で動作するお絵描きアプリ。ユーザーが自由に絵を描くことができ、描いた絵を保存、編集することも可能です。",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "json-server", "ESLint"],
    githubUrl: "https://github.com/kmjak/SketchEase",
    imageUrl: "/sketch-ease.png",
    featured: false,
  },
  {
    id: "テトリス",
    title: "テトリス",
    description:
      "Next.jsを用いたシンプルなテトリスゲーム。ブラウザ上で動作し、キーボード操作でプレイ可能です。著作権の関係で、デプロイやコードの公開は行っておりません。",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "ESLint"],
    imageUrl: "/tetris.png",
    featured: false,
  },
  {
    id: "PoliLink",
    title: "PoliLink",
    description:
      "SwiftUIとGinを使用した、マッチングアプリ。ユーザーが自分に合う政治家を見つけることができるアプリケーションです。",
    technologies: ["SwiftUI", "Swift", "Gin", "Go", "PostgreSQL", "Docker", "JWT", "Firebase"],
    githubUrl: "https://github.com/oca-hackU2025",
    featured: false,
  },
  {
    id: "Key Type",
    title: "Key Type",
    description:
      "タイピング練習アプリ。スコア一覧で過去のスコアと一緒に、その時に間違えたキーとその回数を表示する機能により、苦手なキーについて知ることができます。デプロイ先ではまだ、Vercel PostgreSQLに移行できていないので、単純なプレイしかできません。",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "json-server", "ESLint"],
    githubUrl: "https://github.com/KeyTypeApp/KeyType",
    liveUrl: "https://key-type-3bo2rxp7a-kmjaks-projects.vercel.app",
    imageUrl: "/key-type.png",
    featured: true,
  },
];
